# Generated by Django 3.2.2 on 2021-05-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='project_title',
            new_name='issue_type',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='priority_level',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='company',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
